-- AlterTable
ALTER TABLE "Device" ADD COLUMN     "deployedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Log" ADD COLUMN     "type" TEXT NOT NULL DEFAULT 'SISTEMA';
